#!/usr/bin/env node
'use strict';

/**
 * Interactive first-run setup.
 *
 *   npm run setup
 *
 * - Generates strong AUTH_SECRET / SESSION_SECRET.
 * - Optionally asks for an admin password and a port.
 * - Writes .env.local (won't clobber an existing one unless you confirm).
 * - Seeds config/allowlist.json from the example if it doesn't exist yet.
 *
 * Runs non-interactively with sensible defaults when given --yes (handy for CI
 * or scripted provisioning).
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env.local');
const ALLOWLIST_PATH = path.join(ROOT, 'config', 'allowlist.json');
const ALLOWLIST_EXAMPLE = path.join(ROOT, 'config', 'allowlist.example.json');

const AUTO = process.argv.includes('--yes') || process.argv.includes('-y');

function rand(bytes) {
  return crypto.randomBytes(bytes).toString('hex');
}

function ask(rl, question, fallback) {
  if (AUTO) return Promise.resolve(fallback);
  return new Promise((resolve) => {
    const suffix = fallback ? ` [${fallback}]` : '';
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve((answer || '').trim() || fallback);
    });
  });
}

function askYesNo(rl, question, defYes) {
  if (AUTO) return Promise.resolve(defYes);
  const hint = defYes ? 'Y/n' : 'y/N';
  return new Promise((resolve) => {
    rl.question(`${question} (${hint}): `, (answer) => {
      const a = (answer || '').trim().toLowerCase();
      if (!a) return resolve(defYes);
      resolve(a === 'y' || a === 'yes');
    });
  });
}

function buildEnv({ port, authSecret, sessionSecret, adminPassword }) {
  return `# Generated by "npm run setup" on ${new Date().toISOString()}
# Edit freely. See .env.local.example for all options and explanations.

# ---- Required ----
AUTH_SECRET=${authSecret}

# ---- Admin GUI ----
ADMIN_PASSWORD=${adminPassword}
ADMIN_ENABLED=true
SESSION_SECRET=${sessionSecret}
COOKIE_SECURE=false

# ---- Networking ----
PORT=${port}
HOST=0.0.0.0
AUTH_HEADER=x-auth-token
TRUST_PROXY=true

# ---- Allowlist ----
ALLOWLIST_FILE=config/allowlist.json

# ---- Check behaviour ----
DEFAULT_TIMEOUT_MS=10000
MAX_TIMEOUT_MS=60000
MAX_BODY_BYTES=65536
PING_COUNT=1

# ---- Rate limiting ----
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX=120
LOGIN_RATE_LIMIT_MAX=10

# ---- Logging ----
LOG_LEVEL=debug
`;
}

async function main() {
  console.log('\n=== Uptime Kuma Remote Check — setup ===\n');

  const rl = AUTO ? null : readline.createInterface({ input: process.stdin, output: process.stdout });

  // 1) .env.local
  let writeEnv = true;
  if (fs.existsSync(ENV_PATH)) {
    writeEnv = await askYesNo(
      rl,
      '.env.local already exists. Overwrite it (this regenerates secrets)?',
      false
    );
  }

  if (writeEnv) {
    const port = await ask(rl, 'Port to listen on', '3010');
    const authSecret = rand(32);
    const sessionSecret = rand(32);

    let adminPassword = await ask(
      rl,
      'Admin GUI password (blank = generate a random one)',
      ''
    );
    if (!adminPassword) {
      adminPassword = rand(12);
      console.log(`  -> generated admin password: ${adminPassword}`);
    }

    fs.writeFileSync(ENV_PATH, buildEnv({ port, authSecret, sessionSecret, adminPassword }), {
      mode: 0o600,
    });
    console.log(`\n✔ Wrote ${path.relative(ROOT, ENV_PATH)}`);
    console.log(`  AUTH_SECRET (use as the X-Auth-Token header in Uptime Kuma):`);
    console.log(`    ${authSecret}`);
  } else {
    console.log('• Keeping existing .env.local');
  }

  // 2) allowlist.json
  if (!fs.existsSync(ALLOWLIST_PATH)) {
    const seed = await askYesNo(
      rl,
      'No config/allowlist.json yet. Seed it with example entries?',
      false
    );
    fs.mkdirSync(path.dirname(ALLOWLIST_PATH), { recursive: true });
    if (seed && fs.existsSync(ALLOWLIST_EXAMPLE)) {
      fs.copyFileSync(ALLOWLIST_EXAMPLE, ALLOWLIST_PATH);
      console.log(`✔ Seeded ${path.relative(ROOT, ALLOWLIST_PATH)} from the example (edit it!).`);
    } else {
      fs.writeFileSync(ALLOWLIST_PATH, JSON.stringify({ entries: [] }, null, 2) + '\n');
      console.log(`✔ Created empty ${path.relative(ROOT, ALLOWLIST_PATH)} (add entries via the GUI).`);
    }
  } else {
    console.log(`• Keeping existing ${path.relative(ROOT, ALLOWLIST_PATH)}`);
  }

  if (rl) rl.close();

  console.log('\nNext steps:');
  console.log('  1) npm install        (if you have not already)');
  console.log('  2) npm start          (or: docker compose up -d --build)');
  console.log('  3) Open http://localhost:3010/admin to manage the allowlist');
  console.log('  4) In Uptime Kuma, add an HTTP(s) monitor pointing at:');
  console.log('       https://your-public-host/check?type=ping&host=192.168.1.1');
  console.log('     with a custom header  X-Auth-Token: <your AUTH_SECRET>\n');
}

main().catch((err) => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
